name: test

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"
  UV_VERSION: "0.4.x"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: https://git.joshthomas.dev/mirrors/setup-uv@v4
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Install Protoc
        uses: https://git.joshthomas.dev/mirrors/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies and build
        run: |
          uv sync --frozen
          cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
